# Generated by Django 2.1 on 2018-11-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0002_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('correo', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje', models.TextField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='descripcionMascotra',
            new_name='descripcionMascota',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='imagen',
        ),
        migrations.AddField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(default=11, upload_to='Back/fotos/'),
            preserve_default=False,
        ),
    ]
