# Generated by Django 2.1.3 on 2018-11-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0003_auto_20181108_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descripcionMascota',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(upload_to='./Back/fotos'),
        ),
    ]
