# Generated by Django 2.1.3 on 2018-11-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0005_auto_20181108_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
