# Generated by Django 2.1.3 on 2018-11-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0006_auto_20181108_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(upload_to='', verbose_name='Back/static/media/perros'),
        ),
    ]
