# Generated by Django 2.1.3 on 2018-11-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0008_auto_20181109_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(upload_to='', verbose_name='Back/static/media/perros'),
        ),
    ]
