# Generated by Django 2.1 on 2018-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0014_auto_20181109_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(default='Back/static/media', upload_to='', verbose_name='Back/static/media'),
        ),
    ]
