# Generated by Django 2.1.3 on 2018-11-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0018_auto_20181109_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descripcionMascota',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estadoMascota',
            field=models.CharField(default='Rescatado', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(upload_to='Mascota/%Y%M%D'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='razaMascota',
            field=models.CharField(max_length=30),
        ),
    ]
