# Generated by Django 2.1.3 on 2018-11-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0022_auto_20181110_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
